FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt

COPY streamlit_app /app/streamlit_app

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app/main.py", "--server.address=0.0.0.0", "--server.port=8501"]
