from pathlib import Path
import streamlit as st

from streamlit_app.api_client import health_check, APIClientError
from streamlit_app.ui_helpers import apply_global_styles, render_sidebar_status

st.set_page_config(
    page_title="Image Steganography",
    page_icon="🔐",
    layout="wide",
)

apply_global_styles()
render_sidebar_status(health_check, APIClientError)
st.divider()

BASE_DIR = Path(__file__).resolve().parent

with st.sidebar:
    profile_path = BASE_DIR / "assets" / "images" / "profile.png"

    st.markdown("### Developed by")
    st.markdown("**Phuc Dinh**")

    if profile_path.exists():
        st.image(str(profile_path), width=140)

    st.markdown("[LinkedIn](https://www.linkedin.com/in/huuphucdinh/)")
    st.markdown("[GitHub](https://github.com/larrydinh/Steganography)")


# HERO
st.title("Image Steganography")

# BANNER IMAGE
banner_path = BASE_DIR / "assets" / "images" / "stego_banner.png"

if banner_path.exists():
    st.image(str(banner_path), use_container_width=True)
else:
    st.warning(f"Banner image not found: {banner_path}")

st.markdown("""
<style>
[data-testid="stSidebar"] {
    background-color: #0E1117;
}
[data-testid="stSidebar"] * {
    color: #FAFAFA;
}
</style>
""", unsafe_allow_html=True)

# INTRODUCTION
st.subheader("What is image steganography?")

st.write(
    " Image steganography is a technique for hiding information inside an image in a way that is invisible to the human eye."
)

st.write(
    "Unlike encryption, which makes a message unreadable, steganography hides the existence of the message itself."
)

st.write(
    "In this project, the secret text message is first encrypted with a password and "
    "then embedded into an image. The receiver can later decode the image and "
    "recover the original message using the correct password."
)

st.divider()


# WORKFLOW
st.subheader("How the system works ?")

workflow = [
    (
        "Step 1",
        "Upload Image",
        "Users choose a cover image that will carry the hidden encrypted message."
    ),

    (
        "Step 2",
        "Encrypt Message",
        "Users enter a plaintext message and protect it with a password. "
        "Then, they can either download the generated image to their device "
        "or copy the retrieval code generated by the system to retrieve the image later in the Decode tab."
    ),

    (
        "Step 3",
        "Generate Stego Image",
        "Click the Generate Image button to embed the encrypted message "
        "using different steganography algorithms."
    ),

    (
        "Step 4",
        "Decrypt Message",
        "Users upload the encrypted image or retrieve it using the retrieval code from Step 2. "
        "After entering the correct password, the hidden message will be revealed."
    ),

    (
        "Step 5 (Optional)",
        "Detector",
        "Users upload a suspicious image to identify whether the image contains hidden information."
    )
]
cols = st.columns(5)

for col, (num, title, body) in zip(cols, workflow):
    with col:
        with st.container(border=True):
            st.markdown(f"### {num}")
            st.markdown(f"**{title}**")
            st.write(body)

st.divider()


# DEMO ACTIONS
st.subheader("Try the demo")

cta1, cta2, cta3 = st.columns(3)

with cta1:
    st.page_link(
        "pages/1_Encoder.py",
        label="🔒 Start Encoding",
        use_container_width=True,
    )

with cta2:
    st.page_link(
        "pages/2_Decoder.py",
        label="🔓 Decode Message",
        use_container_width=True,
    )

with cta3:
    st.page_link(
        "pages/3_Detector.py",
        label="🛡 Analyze Suspicious Image",
        use_container_width=True,
    )

st.info(
    "Recommended demo flow: encode a short message first, copy the retrieval code, "
    "then open Decode Message and retrieve the image by code."
)